# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Starter.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread, pyqtSignal
from PyQt5.QtWidgets import QApplication, QMessageBox


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 596)
        Form.setMinimumSize(QtCore.QSize(1000, 596))
        Form.setMaximumSize(QtCore.QSize(1000, 596))
        Form.setBaseSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(False)
        Form.setFont(font)
        self.box_readme = QtWidgets.QGroupBox(Form)
        self.box_readme.setGeometry(QtCore.QRect(170, 10, 660, 81))
        self.box_readme.setObjectName("box_readme")
        self.label_readme = QtWidgets.QLabel(self.box_readme)
        self.label_readme.setGeometry(QtCore.QRect(20, 20, 731, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(10)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_readme.setFont(font)
        self.label_readme.setObjectName("label_readme")
        self.box_devices = QtWidgets.QGroupBox(Form)
        self.box_devices.setGeometry(QtCore.QRect(170, 110, 291, 451))
        self.box_devices.setObjectName("box_devices")
        self.box_devices.setVisible(False)
        self.listWidget_devices = QtWidgets.QListWidget(self.box_devices)
        self.listWidget_devices.setGeometry(QtCore.QRect(10, 50, 271, 391))
        self.listWidget_devices.setObjectName("listWidget_devices")
        self.checkBox_devices = QtWidgets.QCheckBox(self.box_devices)
        self.checkBox_devices.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.checkBox_devices.setObjectName("checkBox_devices")
        self.btn_refresh = QtWidgets.QPushButton(self.box_devices)
        self.btn_refresh.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.btn_refresh.setObjectName("btn_refresh")
        self.box_runcase = QtWidgets.QGroupBox(Form)
        self.box_runcase.setGeometry(QtCore.QRect(540, 110, 291, 451))
        self.box_runcase.setObjectName("box_runcase")
        self.box_runcase.setVisible(False)
        self.listWidget_case = QtWidgets.QListWidget(self.box_runcase)
        self.listWidget_case.setGeometry(QtCore.QRect(10, 50, 271, 391))
        self.listWidget_case.setObjectName("listWidget_case")
        self.checkBox_case = QtWidgets.QCheckBox(self.box_runcase)
        self.checkBox_case.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.checkBox_case.setObjectName("checkBox_case")
        self.btn_path = QtWidgets.QPushButton(self.box_runcase)
        self.btn_path.setGeometry(QtCore.QRect(190, 5, 75, 23))
        self.btn_path.setObjectName("btn_path")
        self.btn_report = QtWidgets.QPushButton(Form)
        self.btn_report.setGeometry(QtCore.QRect(860, 490, 111, 61))
        self.btn_report.setObjectName("btn_report")

        self.btn_start = QtWidgets.QPushButton(Form)
        self.btn_start.setGeometry(QtCore.QRect(860, 420, 111, 61))
        self.btn_start.setObjectName("btn_start")





        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 120, 80))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.box_devices)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_refresh.raise_()
        self.listWidget_devices.raise_()
        self.label_2.raise_()

        self.textEdit = QtWidgets.QTextEdit(self.box_devices)
        self.textEdit.setGeometry(QtCore.QRect(20, 60, 261, 381))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setVisible(False)

        self.pc_starter = QtWidgets.QPushButton(Form)
        self.pc_starter.setGeometry(QtCore.QRect(30, 300, 120, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pc_starter.sizePolicy().hasHeightForWidth())
        self.pc_starter.setSizePolicy(sizePolicy)
        self.pc_starter.setObjectName("pc_starter")
        self.web_starter = QtWidgets.QPushButton(Form)
        self.web_starter.setGeometry(QtCore.QRect(30, 210, 120, 80))
        self.web_starter.setObjectName("web_starter")
        self.android_starter = QtWidgets.QPushButton(Form)
        self.android_starter.setGeometry(QtCore.QRect(30, 120, 120, 80))
        self.android_starter.setObjectName("android_starter")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 420, 120, 112))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.opinion_2 = QtWidgets.QPushButton(self.widget)
        self.opinion_2.setObjectName("opinion_2")
        self.verticalLayout.addWidget(self.opinion_2)
        self.opinion = QtWidgets.QPushButton(self.widget)
        self.opinion.setObjectName("opinion")
        self.verticalLayout.addWidget(self.opinion)
        self.focus_us = QtWidgets.QPushButton(self.widget)
        self.focus_us.setObjectName("focus_us")
        self.verticalLayout.addWidget(self.focus_us)
        self.problems = QtWidgets.QPushButton(self.widget)
        self.problems.setObjectName("problems")
        self.verticalLayout.addWidget(self.problems)

        self.LScriptsRoot = QtWidgets.QLabel(self.box_runcase)
        self.LScriptsRoot.setGeometry(QtCore.QRect(90, 30, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LScriptsRoot.setFont(font)
        self.LScriptsRoot.setText("")
        self.LScriptsRoot.setObjectName("LScriptsRoot")
        #self.LScriptsRoot.setStyleSheet("background-color: red")

        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(330, 190, 471, 121))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(72)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_readme.setText(_translate("Form",
                                             "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                             "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                             "p, li { white-space: pre-wrap; }\n"
                                             "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;  border:none;\n"
                                             "        border-bottom:1px solid white;  padding:2px 4px;border-radius:10px;\">\n"
                                             "<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">使用方法</p>\n"
                                             "<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.点击左侧的启动器按钮，选择执行脚本，安卓设备需要选择执行设备</p>\n"
                                             "<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.点击【启动脚本】按钮</p></body></html>"))

        self.box_readme.setTitle(_translate("Form", "readme"))
        self.box_devices.setTitle(_translate("Form", "List of devices attached"))
        self.checkBox_devices.setText(_translate("Form", "全选"))
        self.btn_refresh.setText(_translate("Form", "刷新"))
        self.label_2.setText(_translate("Form", "输入窗口句柄"))
        self.label_2.setVisible(False)
        self.box_runcase.setTitle(_translate("Form", "选中执行脚本"))
        self.checkBox_case.setText(_translate("Form", "全选"))
        self.btn_path.setText(_translate("Form", "选取路劲"))
        self.btn_report.setText(_translate("Form", "查看结论"))

        self.btn_start.setText(_translate("Form", "启动脚本"))


        self.label.setText(_translate("Form", "自动化工具"))
        self.pc_starter.setText(_translate("Form", "PC-Airtest启动器 "))
        self.web_starter.setText(_translate("Form", "WEB-Airtest启动器"))
        self.android_starter.setText(_translate("Form", "安卓-Airtest启动器"))
        self.opinion_2.setText(_translate("Form", "联系与帮助"))
        self.opinion.setText(_translate("Form", "反馈意见"))
        self.focus_us.setText(_translate("Form", "关注我们"))
        self.problems.setText(_translate("Form", "遇到问题"))
        self.label_3.setText(_translate("Form", "欢迎使用！"))








